import { Button } from '../ui/Button.jsx'
import { Card } from '../ui/Card.jsx'

export function OwnerAgendaCard({ item }) {
  return <Card className="owner-agenda-card"><dl>{Object.entries(item.raw || {}).map(([key, itemValue]) => <div key={key}><dt>{key}</dt><dd>{String(itemValue ?? '—')}</dd></div>)}</dl></Card>
}
export function OwnerMetricCard({ label, amount }) { return <Card className="owner-metric-card"><span>{label}</span><strong>{String(amount)}</strong></Card> }
export function OwnerRulesCard({ onSettings }) { return <Card className="owner-rules-card"><div><strong>Disponibilidade</strong><p>Atualize expediente, dias de atendimento e prazo de cancelamento.</p></div><Button variant="secondary" onClick={onSettings}>Configurar</Button></Card> }
export function DayToggle({ day, selected, onChange }) { return <label className="owner-day"><input type="checkbox" checked={selected} onChange={(event) => onChange(day, event.target.checked)} /><span>{day}</span></label> }
export function AvailabilitySettingsCard({ value, onChange, onDayChange, onSave, saving }) { const days = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb']; return <Card className="owner-settings-card"><div className="owner-form-grid"><label>Início<input type="time" value={value.startTime} onChange={(event) => onChange('startTime', event.target.value)} /></label><label>Fim<input type="time" value={value.endTime} onChange={(event) => onChange('endTime', event.target.value)} /></label><label>Antecedência mínima (horas)<input type="number" min="0" value={value.cancellationHours} onChange={(event) => onChange('cancellationHours', event.target.value)} /></label></div><fieldset><legend>Dias de atendimento</legend><div className="owner-day-list">{days.map((day) => <DayToggle key={day} day={day} selected={value.days.includes(day)} onChange={onDayChange} />)}</div></fieldset><Button onClick={onSave} disabled={saving}>{saving ? 'Salvando...' : 'Salvar configurações'}</Button></Card> }
export function TimeSlotCard({ slot, selected, onSelect }) { return <button className={`owner-slot ${selected ? 'is-selected' : ''}`} type="button" onClick={() => onSelect(slot)}>{slot}</button> }
export function AddAppointmentCard({ clients, services, value, slots, loadingSlots, onChange, onSelectSlot, onSubmit, saving }) { return <Card className="owner-add-card"><div className="owner-form-grid"><label>Cliente<select value={value.clienteId} onChange={(event) => onChange('clienteId', event.target.value)}><option value="">Selecione</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Serviço<select value={value.servicoId} onChange={(event) => onChange('servicoId', event.target.value)}><option value="">Selecione</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label><label>Data<input type="date" value={value.date} onChange={(event) => onChange('date', event.target.value)} /></label></div><div className="owner-slots"><strong>Horários disponíveis</strong>{loadingSlots ? <p>Consultando horários...</p> : slots.length ? <div>{slots.map((slot) => <TimeSlotCard key={slot} slot={slot} selected={value.slot === slot} onSelect={onSelectSlot} />)}</div> : <p>Selecione serviço e data para consultar horários.</p>}</div><Button onClick={onSubmit} disabled={saving || !value.clienteId || !value.servicoId || !value.slot}>{saving ? 'Criando...' : 'Criar agendamento'}</Button></Card> }
export function ApiUnavailableCard({ title, description }) { return <Card className="owner-unavailable"><strong>{title}</strong><p>{description}</p><span>Disponível quando o backend oferecer suporte.</span></Card> }
